Release/1.0.0
fortinet-fortisoar/widget-picklist-as-phases pull request #1
Opened 2024-04-23 11:56 UTC by cs-abhinav-goel

Initial Draft

2024-04-24 07:57 UTC, cs-pranali-chavan commented on widget/view.controller.js
> +  }
import & use widgetBasePath 
widgetBasePath +'images/chevron_inactive_arrow.png'

2024-04-24 07:59 UTC, cs-pranali-chavan requested changes
use widgetBasePath for version updates

2024-04-24 08:21 UTC, cs-suyog-jinturkar commented on widget/info.json
> +    "title": "Info Graphics",
snapshots will be added here as well which will show edit and view panel screenshots

2024-04-25 12:09 UTC, cs-abhinav-goel commented on widget/view.controller.js
> +  }
Done

2024-04-25 12:12 UTC, merged